FROM node:latest

WORKDIR /web 

RUN apt-get update && apt-get install git

RUN git clone https://github.com/fernandojosemoran/frontend-marketing-agency.git

RUN npm install && npm run build

CMD ["npm", "start"]