FROM python:3.12.5

WORKDIR /backend/

COPY backend/ .

RUN pip install -r requirements.txt

# RUN chmod 777 prepare.py

# RUN python3 prepare.py

# ENV PORT=8001

# chmod 777 prepare.py && python3 prepare.py

CMD ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:5000"]

